define([], function(require, exports, module) {
    var tmpl = ['<table cellpadding="0" cellspacing="0" class="table_a" width="100%">',
   '<thead>',
     '<tr class="table_ath">',
       '<td class="txt_cen">时间 <i class="{{d.order1}}"></i></td>',
       '<td class="txt_cen">{{d.ValueTitle}} <i class="{{d.order2}}"></i></td>',
       '<td class="txt_cen">{{d.Value1Title}} <i class="{{d.order3}}"></i></td>',
            '{{# if(d.Value3Title){ }}',
            '<td class="txt_cen">{{d.Value3Title}} <i class="{{d.order4}}"></i></td>',
       '{{# } }}',
     '</tr>',
   '</thead>',
   '<tbody>',
   '{{# for(var i = 0, len = d.List.length; i < len; i++){ }}',
     '<tr>',
       '<td class="txt_cen" width="30%">{{d.List[i].UnitName}}</td>',
        '<td class="txt_cen orange" width="25%">{{d.List[i].Value}}</td>',
        '<td class="txt_cen orange" width="25%">{{d.List[i].Value1}}</td>',
          '{{# if(d.Value3Title){ }}',
            '<td class="txt_cen orange">{{d.List[i].Value3}}</td>',
       '{{# } }}',
     '</tr>',
     '{{# } }}',
   '</tbody>',
'</table>'].join('');
    module.exports = tmpl;
});